### ISSUE TITLE
How to further

### ISSUE THREAD

**Issue by libaibaba** [Francesco149/klbvfs#1]
Thank you for your perfect work, I got the right *. DB now, but what should I do next to get PNG like you? I tried "Python klbvfs.py dump pkg0", it doesn't work -- please forgive my English, it comes from translation

**Comment by Francesco149** [comment]
you need to pass it the directory where the .db files are, not the pkg directory

**Comment by libaibaba** [comment]
Er........ *. DB is in the klbvfs.py directory. Can I request the full CMD code?

**Comment by libaibaba** [comment]
> 嗯........ *。数据库位于klbvfs.py目录中。我可以要求完整的CMD代码吗？

Forgive me for not knowing anything about programming or code

**Comment by Francesco149** [comment]
you need a full copy of your `data/data/com.klab.lovelive.allstars/files/files` and then run klbvfs.py dump on that folder

**Comment by libaibaba** [comment]
> you need a full copy of your `data/data/com.klab.lovelive.allstars/files/files` and then run klbvfs.py dump on that folder

`Python klbvfs.py dump C:\Users\libaibaba\Desktop\love\com.klab.lovelive.allstars\files\files` Like this?

**Comment by libaibaba** [comment]
I realize my stupidity. Now it's my code`Python klbvfs.py dump --types texture C:\Users\libaibaba\Desktop\love\com.klab.lovelive.allstars\files\files`But it still tells me`error: argument --types: invalid choice` --types texture Is it not right?

**Comment by Francesco149** [comment]
try --types=texture

**Comment by libaibaba** [comment]
> try --types=texture

I have found the solution, thank you for the tool!

**Comment by libaibaba** [comment]
> try --types=texture

I don't think that's the right answer. The decrypted file contains a lot of garbage data. Take 0ibhab.Unity3d file for example. The file directory shows 1.73 MB, but the file description in hex view is only 4B C6,After using assetbundleextractor, I get the actual file size of 36KB + 46KB. 0aba0k_0.png file also has a lot of unnecessary data after iend ® B (the end of PNG file). After deletion, PNG can be opened normally. I think the same thing happens on *. JPG, but I don't know the end of JPG file
![DZHFKG`CAZ2QIAXH`5O6RJM](https://user-images.githubusercontent.com/52236285/70618775-9faa8200-1c4e-11ea-8144-2b4cf426f09e.png)
![C6S625P)MC%Y5F)RUK1Z`{D](https://user-images.githubusercontent.com/52236285/70618798-ae913480-1c4e-11ea-87ca-3a2e40a7b3fd.png)
![@B67M7%GXRDR9NQQOU{6$LT](https://user-images.githubusercontent.com/52236285/70618865-c963a900-1c4e-11ea-8e3d-ce41921da298.png)

**Comment by Francesco149** [comment]
yes, this is a known issue. I don't know why some png's have garbage data at the end. you will have to trim them manually. my image viewers open them normally even with the garbage data

**Comment by libaibaba** [comment]
> yes, this is a known issue. I don't know why some png's have garbage data at the end. you will have to trim them manually. my image viewers open them normally even with the garbage data

Thank you again for your tools, and please forgive me for my English. I'm not sure if the translation has made my words arrogant. If so, that's not what I mean

**Comment by Francesco149** [comment]
no problem, I'm happy i was able to help
