### ISSUE TITLE
What is going on, I used colab to decrypt the LLSIFAS file and there was an error

### ISSUE THREAD

**Issue by sanjingward** [Francesco149/klbvfs#11]
What is going on, I used colab to decrypt the LLSIFAS file and there was an error

/content/gdrive/MyDrive//klbvfs.py dump [--types [[/content/data/data/com.klab.lovelive.allstars/files]]] [directories [directories /content/gdrive/MyDrive/LLASSUIT]]

File "<ipython-input-4-33d06fdca1d5>", line 1
    content(/gdrive/MyDrive//klbvfs.py, dump, [--types, [[/content/data/data/com.klab.lovelive.allstars/files]]], [directories, [directories, /content/gdrive/MyDrive/LLASSUIT]])
            ^
SyntaxError: invalid syntax

**Comment by Francesco149** [comment]
never used colab before, but you are most definitely not calling the script correctly

```
/content/gdrive/MyDrive//klbvfs.py dump /content/gdrive/MyDrive/LLASSUIT
```

that might work assuming that LLASSUIT is the `/data/data/com.klab.lovelive.allstars/files/files` directory

**Comment by sanjingward** [comment]
Have complete script correctly？
/content/gdrive/MyDrive/klbvfs.py dump /content/gdrive/MyDrive/LLASSUIT directories: /data/data/com.klab.lovelive.allstars/files/files

File "<ipython-input-18-f2d672e9831a>", line 1
    content(/gdrive/MyDrive/klbvfs.py, dump, /content/gdrive/MyDrive/LLASSUIT, directories:, /data/data/com.klab.lovelive.allstars/files/files)
            ^
SyntaxError: invalid syntax

**Comment by sanjingward** [comment]
/content/gdrive/MyDrive/klbvfs.py query /content/masterdata.db_2ba37a8f39eb4d3f61791e8e88e3427cd3230f0a.db "select sql from sqlite_master;"

?

**Comment by sanjingward** [comment]
> never used colab before, but you are most definitely not calling the script correctly
> 
> ```
> /content/gdrive/MyDrive//klbvfs.py dump /content/gdrive/MyDrive/LLASSUIT
> ```
> 
> that might work assuming that LLASSUIT is the `/data/data/com.klab.lovelive.allstars/files/files` directory

/content/gdrive/MyDrive/klbvfs.py query /content/masterdata.db_2ba37a8f39eb4d3f61791e8e88e3427cd3230f0a.db "select sql from sqlite_master;"

?

**Comment by sanjingward** [comment]
> never used colab before, but you are most definitely not calling the script correctly
> 
> ```
> /content/gdrive/MyDrive//klbvfs.py dump /content/gdrive/MyDrive/LLASSUIT
> ```
> 
> that might work assuming that LLASSUIT is the `/data/data/com.klab.lovelive.allstars/files/files` directory

https://i.imgur.com/QgEOSdA.png
@Francesco149
